#' haplodata4ggplot
#'
#' This function creates a list containing nodes and connections for a haplotype
#' network plot, suitable for use with ggplot2.
#'
#' @param  haploNet_data_object A list containing the haplotype network data
#' named network, and a dataframe named pieseas. The latter contains the
#' proportions of each sample or group of samples for each haplotype. This 
#' object can be generated using the function haploNet_data.
#'
#'  @param method A string indicating the method to use for plotting the network.
#' Options are "pegas" for the pegas package or "fruchtermanreingold" for the
#' Fruchterman-Reingold algorithm.
#'
#'
#' @return Returns a list with two data frames: nodes and connections.
#' The nodes data frame contains the x and y coordinates, size, labels, and
#' proportions of each haplotype. The connections data frame contains the
#' coordinates of the connections between nodes.
#'
#' @details This function prepares the data for plotting haplotype networks, 
#' using either the pegas package or the Fruchterman-Reingold algorithm to
#' determine node positions. The nodes are represented as pie charts, with
#' sizes proportional to haplotype frequencies. The aim of this function is to
#' facilitate the creation of publication-ready haplotype network plots using
#' ggplot2, addressing common issues such as legend overlap with the network.
#' @examples
#' 
#'
#' @export


haplodata4ggplot <- function(haploNet_data_object, method = "pegas") {
    if (!(method %in% c("pegas", "fruchtermanreingold"))) {
        stop("Method must be either 'pegas' or 'fruchtermanreingold'.")
    }
    network <- haploNet_data_object$network
    pieseas <- haploNet_data_object$pieseas
    if (is.null(pieseas) || nrow(pieseas) == 0) {
        stop("No valid haplotypes found. Please check your input data.")
    }
    if (is.null(network)) {
        if (nrow(pieseas) > 1) {
            stop("The haplotype network is empty but more than one haplotype found. Please check your input data.")
        }
        warning("The haplotype network is empty. Only one haplotype found.")
        nodes <- cbind(
            data.frame(
                x = 0,
                y = 0,
                size = rowSums(pieseas),
                labels = rownames(pieseas)
            ),
            pieseas
        )
        connections <- data.frame(x = 0, y = 0, x.1 = 0, y.1 = 0)
    } else {
        if (method == "fruchtermanreingold") {
            tryCatch(
                {
                    net <- try(network::network(matrix(network[,1:2], ncol = 2), matrix.type = 'edgelist'), silent = TRUE)
                    haplot <- network::as.matrix.network.adjacency(net)
                    haplot <- do.call(sna::gplot.layout.fruchtermanreingold, list(haplot, NULL))
                    haplot <- data.frame(x = haplot[, 1], y = haplot[, 2])

                    edges <- network::as.matrix.network.edgelist(net)
                },
                error = function(e) {
                    cat("The haplotype network plot could not be generated by the fruchtermanreingold method.\n")
                    cat("Reason:", e$message, "\n")
                    stop("Plot error.")
                }
            )

            connections <- data.frame(haplot[edges[, 1], ], haplot[edges[, 2], ])
            connections$dist <- sqrt((connections$x.1 - connections$x)^2 + (connections$y.1 - connections$y)^2)
            # find the biggest circle radius
            max_size_pos <- which.max(rowSums(pieseas))
            min_dist_from_larger_circle <- connections$dist[which.min(connections$dist[edges[, 1] == max_size_pos | edges[, 2] == max_size_pos])]

            if (min_dist_from_larger_circle < max(rowSums(pieseas))) {
                scale_factor <- max(rowSums(pieseas)) / min_dist_from_larger_circle * 1.1
                origin <- haplot[max_size_pos, ]
                haplot <- data.frame(
                    x = origin$x + (haplot$x - origin$x) * scale_factor,
                    y = origin$y + (haplot$y - origin$y) * scale_factor
                )
                connections <- data.frame(haplot[edges[, 1], ], haplot[edges[, 2], ])
            }
            haplot$size <- rowSums(pieseas)
            haplot$labels <- rownames(pieseas)
            nodes <- cbind(
                haplot,
                pieseas
            )
        } else {
            tryCatch(
                {
                    pdf(NULL)
                    haplot <-
                        plot(network,
                            size = attr(network, "freq"), threshold = 0,
                            fast = T, show.mutation = 0
                        )
                    dev.off()
                },
                error = function(e) {
                    cat("Custom error: The haplotype network plot could not be generated.\n")
                    cat("Reason:", e$message, "\n")
                    stop("Plot error.")
                }
            )
            nodes <- cbind(
                data.frame(
                    x = haplot$xx,
                    y = haplot$yy,
                    size = haplot$size,
                    labels = haplot$labels
                ),
                pieseas
            )
            connections <- data.frame(nodes[haplot$link[, 1], c(1, 2)], nodes[haplot$link[, 2], c(1, 2)])
        }
    }

    haplot <- list(
        nodes = nodes,
        connections = connections
    )

    return(haplot)
}
